### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by logickphp** [TwanoO67/ng2-admin-lte#54] opened 2016-12-14 11:07 UTC
npm start                                                 ✓  10355  12:00:22 

> ng2-admin-lte@0.7.0 start /var/www/sources/6_INVEN_VEHIC/ng2-admin-lte
> ng serve

Unexpected token [
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-ide/addon/commands/serve.js:14:33)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-ide/index.js:5:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Function.Addon.lookup (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-cli/angular-cli/lib/models/addon.js:835:19)
    at /var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-cli/angular-cli/lib/models/addons-factory.js:47:36
    at visit (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-cli/angular-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-cli/angular-cli/lib/utilities/DAG.js:82:7)
    at AddonsFactory.initializeAddons (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-cli/angular-cli/lib/models/addons-factory.js:44:9)
    at Project.initializeAddons (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-cli/angular-cli/lib/models/project.js:374:36)
    at Project.eachAddonCommand (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-cli/angular-cli/lib/models/project.js:425:10)
    at module.exports (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-cli/angular-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/angular-cli/angular-cli/lib/cli/cli.js:34:26)
    at tryCatch (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/node_modules/rsvp/dist/rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)

npm ERR! Linux 3.19.0-39-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "start"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ng2-admin-lte@0.7.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-admin-lte@0.7.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-admin-lte package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-admin-lte
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-admin-lte
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/sources/6_INVEN_VEHIC/ng2-admin-lte/npm-debug.log

**Comment by Erik1288** [comment] 2016-12-15 07:21
'ng serve' failed. Looks like you haven't installed angular-cli yet.

**Comment by Erik1288** [comment] 2016-12-15 07:30
I encountered a similar problem.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1_1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! ng2-admin-lte@0.7.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-admin-lte@0.7.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-admin-lte package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-admin-lte
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-admin-lte
npm ERR! There is likely additional logging output above.

**Comment by TwanoO67** [comment] 2016-12-15 07:31
I tried a fresh install, for me it's working

But I always add tested on a node > 5

Furthermore you can do " npm install -g angular-cli" 

( I should add that step on read me..)

**Comment by TwanoO67** [comment] 2016-12-15 07:37
Can you try re installing with this 

Rm -rf node_modules
Git checkout 4992d8cb78e2095f7b978acd173454bf0a5cd4a0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
Npm install

**Comment by TwanoO67** [comment] 2016-12-15 07:37
Oh

**Comment by TwanoO67** [comment] 2016-12-18 09:34
Ok I somehow achieve to encouter the same problem, and now I can't fix it neither ^^

Will keep you in touch if if found a fix

**Comment by TwanoO67** [comment] 2016-12-18 09:51
Ok, so for me it was related to angular-ide dependencies.
Si it should be fixed by the last commit.

@Erik1288 and @logickphp , could you: 
rm -rf node_modules
git pull
npm cache clean
npm install

And confirm that the issue is fixed ?

**Comment by reactops** [comment] 2016-12-18 15:25
Sorry guys...it was my fault...
The dependency installed automatically by Eclipse Webclipse plugin. I haven't noticed it.
I will test my future Pull Requests in clean Docker environment for consistency.

**Comment by Erik1288** [comment] 2016-12-21 03:18
I have resolved this by updating `node` version to v6.9.2

**Closed** 2016-12-21 06:26 UTC
